// Import Mongoose for MongoDB object modeling
import mongoose from "mongoose";

// Define the Question schema for storing individual interview questions and answers
// Each question belongs to a specific session and contains AI-generated content
const questionsSchema = new mongoose.Schema(
  {
    // Reference to the session this question belongs to
    session: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Session", // References the Session model
      required: true, // Every question must belong to a session
    },

    // The interview question text generated by AI
    question: {
      type: String,
      required: true, // Question text is mandatory
    },

    // The detailed answer/explanation for the question
    // Contains comprehensive information including examples and best practices
    answer: {
      type: String,
      required: true, // Answer is mandatory
    },

    // Whether this specific question is pinned/bookmarked by the user
    // Allows users to mark important questions for quick reference
    isPinned: {
      type: Boolean,
      default: false, // Default to not pinned
    },
  },
  {
    // Automatically add createdAt and updatedAt timestamps
    timestamps: true,
  },
);

// Create the Question model from the schema
// This model provides methods for database operations on question documents
const Question = mongoose.model("Question", questionsSchema);

// Export the Question model for use in controllers and other parts of the application
export default Question;

// let question = {
//   session: "Session_ID",
//   questions: "What is node",
//   ans: "thi is ans",
// };
